default:
  image: golang:alpine

stages:
  - test
  - build
  - upload
  - release

variables:
  TAG: '$CI_COMMIT_TAG'
  NAME: 'systemreport'
  X86_64_BINARY: '${NAME}-${TAG}.tar.gz'

sast:
  stage: test

include:
- template: Security/SAST.gitlab-ci.yml

build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${NAME}
    - tar -czvf ${X86_64_BINARY} ${NAME}
  artifacts:
    paths:
      - ${X86_64_BINARY}

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - 'echo ${NAME} ${TAG} Upload'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${X86_64_BINARY} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${NAME}/${TAG}/${X86_64_BINARY}"'

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - echo "${NAME} ${TAG} Release"
  release:
    name: '${NAME} ${TAG} Release'
    description: 'Another release of $NAME'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: '${X86_64_BINARY}'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${NAME}/${TAG}/${X86_64_BINARY}'
