name: Release Workflow

on:
  push:
    # branches:
    #   - main
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'  # Specify the Go version

    - name: Building and Archive CLI Binary
      run: |
        go mod tidy
        go build -o systemreport .
        tar -czvf systemreport.tar.gz systemreport 

    - name: Create Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
      run: |
          gh release create ${GITHUB_REF##*/} systemreport.tar.gz

